using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShippingByMarket
{
    class PedidoFedex
    {
        public string FullTrakingId { get; set; }
        public string BilltoAccountNumber { get; set; }
        public string InvoiceDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string StoreID { get; set; }
        public string OriginalAmountDue { get; set; }
        public string CurrentBalance { get; set; }
        public string Payor { get; set; }
        public string GroundTrackingIDPrefix { get; set; }
        public string ExpressorGroundTrackingID { get; set; }
        public string TransportationChargeAmount { get; set; }
        public string NetChargeAmount { get; set; }
        public string ServiceType { get; set; }
        public string GroundService { get; set; }
        public string ShipmentDate { get; set; }
        public string PODDeliveryDate { get; set; }
        public string PODDeliveryTime { get; set; }
        public string PODServiceAreaCode { get; set; }
        public string PODSignatureDescription { get; set; }
        public string ActualWeightAmount { get; set; }
        public string ActualWeightUnits { get; set; }
        public string RatedWeightAmount { get; set; }
        public string RatedWeightUnits { get; set; }
        public string NumberofPieces { get; set; }
        public string BundleNumber { get; set; }
        public string MeterNumber { get; set; }
        public string TDMasterTrackingID { get; set; }
        public string ServicePackaging { get; set; }
        public string DimLength { get; set; }
        public string DimWidth { get; set; }
        public string DimHeight { get; set; }
        public string DimDivisor { get; set; }
        public string DimUnit { get; set; }
        public string RecipientName { get; set; }
        public string RecipientCompany { get; set; }
        public string RecipientAddressLine1 { get; set; }
        public string RecipientAddressLine2 { get; set; }
        public string RecipientCity { get; set; }
        public string RecipientState { get; set; }
        public string RecipientZipCode { get; set; }
        public string RecipientCountryTerritory { get; set; }
        public string ShipperCompany { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAddressLine1 { get; set; }
        public string ShipperAddressLine2 { get; set; }
        public string ShipperCity { get; set; }
        public string ShipperState { get; set; }
        public string ShipperZipCode { get; set; }
        public string ShipperCountryTerritory { get; set; }
        public string OriginalCustomerReference { get; set; }
        public string OriginalRef2 { get; set; }
        public string OriginalRef3PONumber { get; set; }
        public string OriginalDepartmentReferenceDescription { get; set; }
        public string UpdatedCustomerReference { get; set; }
        public string UpdatedRef2 { get; set; }
        public string UpdatedRef3PONumber { get; set; }
        public string UpdatedDepartmentReferenceDescription { get; set; }
        public string RMA { get; set; }
        public string OriginalRecipientAddressLine1 { get; set; }
        public string OriginalRecipientAddressLine2 { get; set; }
        public string OriginalRecipientCity { get; set; }
        public string OriginalRecipientState { get; set; }
        public string OriginalRecipientZipCode { get; set; }
        public string OriginalRecipientCountryTerritory { get; set; }
        public string ZoneCode { get; set; }
        public string CostAllocation { get; set; }
        public string AlternateAddressLine1 { get; set; }
        public string AlternateAddressLine2 { get; set; }
        public string AlternateCity { get; set; }
        public string AlternateStateProvince { get; set; }
        public string AlternateZipCode { get; set; }
        public string AlternateCountryTerritoryCode { get; set; }
        public string CrossRefTrackingIDPrefix { get; set; }
        public string CrossRefTrackingID { get; set; }
        public string EntryDate { get; set; }
        public string EntryNumber { get; set; }
        public string CustomsValue { get; set; }
        public string CustomsValueCurrencyCode { get; set; }
        public string DeclaredValue { get; set; }
        public string DeclaredValueCurrencyCode { get; set; }
        public string CommodityDescription { get; set; }
        public string CommodityCountryTerritoryCode { get; set; }
        public string CommodityDescription1 { get; set; }
        public string CommodityCountryTerritoryCode1 { get; set; }
        public string CommodityDescription2 { get; set; }
        public string CommodityCountryTerritoryCode2 { get; set; }
        public string CommodityDescription3 { get; set; }
        public string CommodityCountryTerritoryCode3 { get; set; }
        public string CurrencyConversionDate { get; set; }
        public string CurrencyConversionRate { get; set; }
        public string MultiweightNumber { get; set; }
        public string MultiweightTotalMultiweightUnits { get; set; }
        public string MultiweightTotalMultiweightWeight { get; set; }
        public string MultiweightTotalShipmentChargeAmount { get; set; }
        public string MultiweightTotalShipmentWeight { get; set; }
        public string GroundTrackingIDAddressCorrectionDiscountChargeAmount { get; set; }
        public string GroundTrackingIDAddressCorrectionGrossChargeAmount { get; set; }
        public string RatedMethod { get; set; }
        public string SortHub { get; set; }
        public string EstimatedWeight { get; set; }
        public string EstimatedWeightUnit { get; set; }
        public string PostalClass { get; set; }
        public string ProcessCategory { get; set; }
        public string PackageSize { get; set; }
        public string DeliveryConfirmation { get; set; }
        public string TenderedDate { get; set; }
        public string TrackingIDChargeDescription { get; set; }
        public string TrackingIDChargeAmount { get; set; }
        public string TrackingIDChargeDescription1 { get; set; }
        public string TrackingIDChargeAmount1 { get; set; }
        public string TrackingIDChargeDescription2 { get; set; }
        public string TrackingIDChargeAmount2 { get; set; }
        public string TrackingIDChargeDescription3 { get; set; }
        public string TrackingIDChargeAmount3 { get; set; }
        public string TrackingIDChargeDescription4 { get; set; }
        public string TrackingIDChargeAmount4 { get; set; }
        public string TrackingIDChargeDescription5 { get; set; }
        public string TrackingIDChargeAmount5 { get; set; }
        public string TrackingIDChargeDescription6 { get; set; }
        public string TrackingIDChargeAmount6 { get; set; }
        public string TrackingIDChargeDescription7 { get; set; }
        public string TrackingIDChargeAmount7 { get; set; }
        public string TrackingIDChargeDescription8 { get; set; }
        public string TrackingIDChargeAmount8 { get; set; }
        public string TrackingIDChargeDescription9 { get; set; }
        public string TrackingIDChargeAmount9 { get; set; }
        public string TrackingIDChargeDescription10 { get; set; }
        public string TrackingIDChargeAmount10 { get; set; }
        public string TrackingIDChargeDescription11 { get; set; }
        public string TrackingIDChargeAmount11 { get; set; }
        public string TrackingIDChargeDescription12 { get; set; }
        public string TrackingIDChargeAmount12 { get; set; }
        public string TrackingIDChargeDescription13 { get; set; }
        public string TrackingIDChargeAmount13 { get; set; }
        public string TrackingIDChargeDescription14 { get; set; }
        public string TrackingIDChargeAmount14 { get; set; }
        public string TrackingIDChargeDescription15 { get; set; }
        public string TrackingIDChargeAmount15 { get; set; }
        public string TrackingIDChargeDescription16 { get; set; }
        public string TrackingIDChargeAmount16 { get; set; }
        public string TrackingIDChargeDescription17 { get; set; }
        public string TrackingIDChargeAmount17 { get; set; }
        public string TrackingIDChargeDescription18 { get; set; }
        public string TrackingIDChargeAmount18 { get; set; }
        public string TrackingIDChargeDescription19 { get; set; }
        public string TrackingIDChargeAmount19 { get; set; }
        public string TrackingIDChargeDescription20 { get; set; }
        public string TrackingIDChargeAmount20 { get; set; }
        public string TrackingIDChargeDescription21 { get; set; }
        public string TrackingIDChargeAmount21 { get; set; }
        public string TrackingIDChargeDescription22 { get; set; }
        public string TrackingIDChargeAmount22 { get; set; }
        public string TrackingIDChargeDescription23 { get; set; }
        public string TrackingIDChargeAmount23 { get; set; }
        public string TrackingIDChargeDescription24 { get; set; }
        public string TrackingIDChargeAmount24 { get; set; }
        public string ShipmentNotes { get; set; }
    }

}
